language: node_js

node_js:
  - stable

services:
  - mongodb

install:
  - npm install

before_script:
  - npm install grunt-cli -g

script:
  - npm run cover

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"